### ISSUE TITLE
Watermark API doesn't work with this project 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-MVC#18]
This issue is raised in https://forum.groupdocs.com/t/adding-watermark-in-editor-app/8952

When we add GroupDocs.Watermark for .NET reference in this project. Although reference is installed successfully but still can't access Watermark API classes or namespaces. 
Even can't add "using GroupDocs.Watermark" inspite of the fact that NuGet or the reference was added properly.

**Comment by Pavel-Teplitsky** [comment]
@atirtahirgroupdocs Sorry for such a long delay. Please try to do next:
1. Remove GroupDocs.Watermark dependency
2. Clean solution
3. Manually remove bin and obj directories
4. Restart VS
5. Install GroupDocs.Watermark
