### ISSUE TITLE
Word document with Fillable form is not working

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-MVC#19]
https://forum.groupdocs.com/t/fillable-form-using-groupdocs-editor/8991
Hi,
Please find the problematic file attached, when loaded in this application. Application doesn't allow to enter data in the form fields. Also, could we export such a Word file to PDF with editable form fields?
[Fillable Form.zip](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-MVC/files/5508981/Fillable.Form.zip)
 Please take a look.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, we are working on a fix for this issue.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs,
The issue has been fixed, please checkout latest commit from master branch.

**Note** that re-saving will not work as expected due to the current features of the library.
For more info please refer to **EDITORNET-1902** ticket.
