### ISSUE TITLE
Update example project using latest version of the API without legacy objects/methods

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-MVC#7]
This issue is raised in https://forum.groupdocs.com/t/recommended-client-side-editor/7852
Hi,
Currently this MVC example project is using API version 19.5, a lot of methods/objects in this version are now deprecated and marked as legacy. 
Can you please share a plan to publish a new release of this project using latest API version (19.11)?
One of the users is interested in this showcase project but wants to see latest version integration and usage in the project.
Thanks

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, we are now discussing the possibility and time estimation for making this upgrade, we will let you know about the status at start of the next week.

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

GroupDocs.Editor API has been updated to latest version 20.2 which includes major fixes and improvements.
Checkout master branch to get latest changes.

Regards
